image:
  file: .gitpod.Dockerfile

tasks:
  - name: doc
    init: cargo +nightly doc --all-features --no-deps
    command: miniserve --index benimator/index.html target/doc

  - name: test
    init: |
      cp .cargo/fast_compiles_config .cargo/config.toml
      cargo update
      cargo doc --all-features --no-deps
      cargo clippy --all-features --all-targets
      cargo test --all-features
      cargo test
    command: |
      cargo watch \
        -x 'test --tests' \
        -x 'test --all-features --tests' \
        -x 'test --all-features' \
        -x 'clippy --all-features --all-targets' \
        -x 'doc --all-features --no-deps'

vscode:
  extensions:
    - belfz.search-crates-io
    - matklad.rust-analyzer
    - serayuzgur.crates
    - bungcip.better-toml

ports:
  - name: example (wasm)
    port: 1334
    visibility: private
    onOpen: notify

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: false
