[package]
name = "benimator"
version = "0.1.0" # auto-version
authors = ["Jonathan Cornaz"]
edition = "2018"
license = "MIT"
description = "A sprite sheet animation plugin for Bevy"
repository = "https://github.com/jcornaz/benimator"
keywords = ["game", "gamedev", "anmiation", "bevy"]
categories = ["game-development"]

[dependencies]
bevy_core = "^0.5.0"
bevy_ecs = "^0.5.0"
bevy_app = "^0.5.0"
bevy_reflect = "^0.5.0"
bevy_sprite = "^0.5.0"

[dev-dependencies]
bevy = { version = "^0.5.0", default-features = false, features = ["render", "bevy_wgpu", "x11", "png"] }
rstest = "^0.7.0" # Newer versions are incompatible with bevy 0.5
