[package]
name = "animism"
version = "0.0.0"
authors = ["Jonathan Cornaz"]
edition = "2018"

[profile.dev]
opt-level = 1

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1

[dependencies]
bevy = { version = "^0.5.0", default-features = false }
