allow-branch = ["main"]
consolidate-commits = true
consolidate-pushes = true
pre-release-commit-message = "chore: Release"
tag-prefix = "v"
dev-version = false

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "## \\[Unreleased\\]"
replace = "## [Unreleased]\n\n\n\n## [{{version}}] - {{date}}"
exactly = 1
prerelease = true

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "\\.\\.\\.HEAD"
replace = "...v{{version}}"
exactly = 1
prerelease = true

[[pre-release-replacements]]
file = "README.md"
search = "heron = \"[0-9a-z\\.-]+\""
replace = "heron = \"{{version}}\""
prerelease = true
