version: 2.1

workflows:
  ci:
    jobs:
      - test
      - test-all-features
      - check-documentation
      - check-code-style
      - deny-unwanted-deps
      - deny-unused-deps
  release:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only: [main, rc, beta, alpha]
    jobs:
      - test
      - test-all-features
      - check-documentation
      - release:
          requires: [test, test-all-features, check-documentation]
          context: [crates-io, github]

executors:
  msrv:
    docker:
      - image: cimg/rust:1.59
  stable:
    docker:
      - image: cimg/rust:1.61
  release:
    docker:
      - image: cimg/rust:1.61-node

jobs:
  test:
    executor: msrv
    steps:
      - checkout
      - run: cargo check --all-targets
      - run: cargo test
  test-all-features:
    executor: msrv
    steps:
      - checkout
      - run: cargo check --all-features --all-targets
      - run: cargo test --all-features
  check-documentation:
    executor: stable
    steps:
      - checkout
      - run: cargo doc --all-features --no-deps
  check-code-style:
    executor: stable
    steps:
      - checkout
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features --all-targets
  deny-unwanted-deps:
    executor: stable
    steps:
      - checkout
      - run: cargo install cargo-deny
      - run: cargo deny check
  deny-unused-deps:
    executor: stable
    steps:
      - checkout
      - run: rustup toolchain install nightly 
      - run: cargo install cargo-udeps
      - run: cargo +nightly udeps
  release:
    executor: release
    steps:
      - checkout
      - run: npm install --no-save conventional-changelog-conventionalcommits @semantic-release/exec
      - run: npx semantic-release
