name: dependencies

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

  schedule:
    - cron: '0 0 */10 * *'

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - run: cargo install cargo-deny
      - run: cargo deny check advisories
      - run: cargo deny check licenses
      - run: cargo deny check sources
